version: '3.9'
services:
  photos:
    build:
      args:
        build: false
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173/tcp
    volumes:
      - ./packages:/app/packages
