name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Docker CLI
        run: |
          apk add --no-cache docker-cli

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.dylan.is
          username: dylan
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          build-args: build=true
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            git.dylan.is/dylan/photos:latest
            git.dylan.is/dylan/photos:${{ github.sha }}
